
# ############################
# Ubuntu
# ############################
- name: install basic dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    update_cache: yes
    force: yes
  when: ansible_distribution == 'Ubuntu'

- name: removing older versions of Docker
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_distribution == 'Ubuntu'

- name: add Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} test"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: install Docker CE
  apt:
    pkg:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    update_cache: yes
    force: yes
  when: ansible_distribution == 'Ubuntu'

- name: "Adding {{ ansible_facts['env']['SUDO_USER'] }} to group docker"
  user:
    name: "{{ ansible_facts['env']['SUDO_USER'] }}"
    group: docker
    append: yes
  when: ansible_distribution == 'Ubuntu'
